# Generated by Django 3.0.7 on 2020-11-16 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
