# Generated by Django 3.0.7 on 2020-12-03 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='ip',
        ),
    ]
