# Generated by Django 3.0.7 on 2020-12-08 14:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='entr_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ip',
            name='ip_address',
            field=models.GenericIPAddressField(),
        ),
    ]
