# Generated by Django 3.0.7 on 2020-12-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20201208_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
