# Generated by Django 3.0.7 on 2020-11-10 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_remove_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
