# Generated by Django 3.0.7 on 2020-12-05 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
